language: java
email:
  recipients:
  - eamon.foy@mycit.ie
jdk:
- oraclejdk8
install:
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- ./mvnw clean install sonar:sonar -Dsonar.projectKey=BravoTeam2018_DetectCloneRFID -Dsonar.organization=bravoteam2018-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=f37b3e181a488a1bb493c7ff59d0d686903bb7a5
env:
  global:
before_install:
- chmod +x mvnw
